apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  # deployment labels
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion }}"
        envFrom:
        - configMapRef:
            name: cart